### PR TITLE
Add HR tag helper

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by hanneskaeufler** [comment]
Nice, do you see a use-case for a hr with content? If not it might be sufficient to add it to `EMPTY_TAGS` exclusively?

**Comment by andyw8** [comment]
@hanneskaeufler good point, I'll update the PR.

**Comment by andyw8** [comment]
@hanneskaeufler now updated.

**Comment by paulcsmith** [comment]
Looks good! Thank you :)

**Pull request merged**
