### PR TITLE
Add ability to pass crystal --error-trace to lucky watch task.

### LINKED ISSUE #947: Add --error-trace to lucky watch / lucky dev
When running your app through `lucky dev`, there's no way to pass `--error-trace` currently. We need a way to proxy that down to [this command](https://github.com/luckyframework/lucky/blob/master/tasks/watch.cr#L210-L211).

We could have `lucky dev --error-trace` or maybe you just edit your Procfile.dev (which would probably need to happen anyway), and update `lucky watch --error-trace`.

### PR DESCRIPTION
**Pull request by jwoertink**
## Purpose
Fixes #947 

## Description
Allows you to pass crystal's `--error-trace` flag in to `lucky watch` command. When you run `lucky dev`, and encounter a compiler error, you'll be given the full trace each time.

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [x] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Comment by paulcsmith** [comment]
Added an issue to Crystal here: https://github.com/crystal-lang/crystal/issues/8374

**Comment by jwoertink** [comment]
I've added a little todo note for us to revisit if that crystal issue ever becomes a thing. I think getting this merged in for now will be good just so people can take advantage of the full errors. I'll merge once these builds finish and pass.

**Comment by paulcsmith** [comment]
Agreed! Thanks @jwoertink

**Comment by bdtomlin** [comment]
@jwoertink, thanks for this. Super helpful!

**Comment by Napolskih** [comment]
image

image

image

@jwoertink not fixed!

**Comment by jwoertink** [comment]
@Napolskih You have to make sure that your `lucky -v` is on at least 1.0.0 or later. Since 1.1.0 is the latest as of right now, you should upgrade to that.

image

**Comment by Napolskih** [comment]
image

**Comment by jwoertink** [comment]
What version is listed in your `shard.yml` file?

**Comment by Napolskih** [comment]
Thanks I got it.

Lucky_jumpstart needs to be removed from the documentation or updated.

image

**Pull request merged**
