### PR TITLE
Adds remaining missing html tags

### PR DESCRIPTION
**Pull request by rmarronnier**
## Purpose

Follow up to #1317

All added tags are all present and not deprecated in the current HTML Living Standard

https://developer.mozilla.org/en-US/docs/Web/HTML/Element was my source of information

## Checklist
* [ ] - An issue already exists detailing the issue/or feature request that this PR fixes
* [ ] - All specs are formatted with `crystal tool format spec src`
* [ ] - Inline documentation has been added and/or updated
* [x ] - Lucky builds on docker with `./script/setup`
* [x ] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Review by stephendolan — APPROVED** [review]
Looks pretty good! Thanks for submitting this, @rmarronnier!

@jwoertink / @matthewmcgarvey ,

Thoughts on breaking out this array to separate lines? It'll make the file super long, but would make reviewing diffs like this way easier 😄

**Comment by rmarronnier** [comment]
Good idea. Made it into multilines ;-) 

It'll allow commenting specific tags if needed.

**Comment by jwoertink** [comment]
I wonder how some of these tags will affect some apps 🤔  Like, I use the variable `data` all over the place on my pages. Also, how common are some of these tags? You can always do `tag("data")`, so I'm wondering if some of these tags that are less common would be better as just using `tag` as needed. It's nice to have every tag to make our set complete, but if that comes at a cost of existing apps getting errors similar to https://github.com/luckyframework/lucky/issues/1414 then that might not be good. @stephendolan do you think there's any issue here?

But as for the multi-line, I think that's fine 👍

**Comment by stephendolan** [comment]
@jwoertink My gut says we should work through those issues as they come up and support the full HTML spec by default for our Lucky HTML views.

Otherwise, we'll probably end up in a position where we have to continually justify why some tags are included and others aren't, perpetually bike-shedding with folks that have clear use cases in their apps where specific tag helpers would be beneficial.

**Comment by jwoertink** [comment]
@stephendolan Sounds good to me!

**Review by jwoertink — APPROVED** [review]

**Pull request merged**
