### PR TITLE
New 'm' method for mounting components

### LINKED ISSUE #1049: Shortcut for mounting
I mount a **lot** of components. I wonder if we shuold add some kind of shortcut method for `mount`?

```crystal
mount MyButton.new
m MyButton.new
```

Thoughts?

### PR DESCRIPTION
**Pull request by paulcsmith**
Closes #1049

### CODE REVIEW

**Comment by paulcsmith** [comment]
Thanks for the review!

**Comment by wout** [comment]
Is this fully implemented? Our app is now in the master branch and I'm getting those warnings:

```bash
web          | In src/pages/main_layout.cr:21:7
web          | 
web          |  21 | mount Shared::LayoutHead.new(seo: page_seo, context: context)
web          |       ^----
web          | Warning: Deprecated About::ShowPage#mount. Use `#m` instead. Example: m(MyComponent, arg1: 123)
```

But when I follow the instructions:

```bash
web          | In src/pages/main_layout.cr:21:7
web          | 
web          |  21 | m Shared::LayoutHead.new(seo: page_seo, context: context)
web          |       ^
web          | Error: no overload matches 'Pricing::IndexPage#m' with type Shared::LayoutHead
web          | 
web          | Overloads are:
web          |  - Lucky::MountComponent#m(component : Lucky::BaseComponent.class, *args, **named_args)
web          |  - Lucky::MountComponent#m(component : Lucky::BaseComponent.class, *args, **named_args, &block)
```

**Comment by jwoertink** [comment]
@wout You don't call `.new` with `m`. Just `m(Shared::LayoutHead, set: page_seo, context: context)`

**Comment by wout** [comment]
Aaaah, that explains it. I didn't realize usage has changed. Thanks!

**Pull request merged**
