### PR TITLE
Pass context to components through mount

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
## Purpose

Related to https://github.com/luckyframework/lucky/issues/1152

## Description

Instead of implementing `mount_defaults` the main code that we want passed down into components without being asked for is the context. This adds it to be passed in just like view is.

### CODE REVIEW

**Comment by stephendolan** [comment]
@matthewmcgarvey This is awesome, and if we can extend `@context` to hold more than just `HTTP::Server::Context` (like `current_site` or `current_user`), then I think the need for `mount_defaults` goes away entirely!

I'm having trouble visualizing when I'd hit the scenario you describe here:
> or set it with 'context(@context)' before rendering.

What would that look like in an app to render a component without `mount`?

**Review by jwoertink — APPROVED** [review]
That's funny, I had the same thought just the other day! Really, this is the big one. Anything else like `current_user` or `current_site` can still be as needed. This was really the only annoying one. I dig it!

**Review by stephendolan — APPROVED** [review]

**Comment by matthewmcgarvey** [comment]
On my phone so I can't link to the specific lines but at the bottom of this file where components can be provided also needs to pass in the context https://www.github.com/luckyframework/lucky/tree/master/src%2Flucky%2Frenderable.cr

**Comment by stephendolan** [comment]
Ah, right!

**Review by jwoertink — APPROVED** [review]
Yup. Looks good to me

**Comment by stephendolan** [comment]
Likewise! I don't see any downsides to getting this merged.

**Pull request merged**
