### PR TITLE
Generate docs for CI

### PR DESCRIPTION
**Pull request by mdwagner**
## Purpose
Generates docs (`crystal docs`) for Travis CI
Issue: https://github.com/luckyframework/lucky/issues/988

## Description
On any commit into `master`, this will auto-deploy documentation generated from `crystal docs` on Github Pages.

**Travis CI config needs to be updated to include GITHUB_TOKEN environment variable**
The GITHUB_TOKEN, which is a [github personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), only needs the `public_repo` scope.

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [x] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`
* [ ] - Update Travis CI config to include GITHUB_TOKEN (possibly enable only for `master` branch)

### CODE REVIEW

**Comment by jwoertink** [comment]
Awesome! I don't have access to the travis account, so I'll let @paulcsmith handle this, but thanks for tackling this. It really will be a huge thing to help people learn.

**Comment by mdwagner** [comment]
@jwoertink Happy to help! It was something I had just done for one of my own projects that I thought it would make sense to do while it's still fresh in my mind. Also, I wanted to start contributing to this project (+ other related projects), and this seemed like a good start!

**Comment by paulcsmith** [comment]
@mdwagner This looks cool! So does this automatically create a branch with the docs or something? I've never use this feature of Travis so I'm not 100% sure I understand what it is doing

**Comment by mdwagner** [comment]
@paulcsmith AFAIK, this is how it works:
1. Travis CI will generate the docs inside the CI job (master only).
2. Travis CI will push the contents of `docs/` to the repository's `gh-pages` branch, which is a special branch that Github uses to create Github Pages. I think this branch is an orphan, meaning it doesn't contain any code (just web deployment files) and can't compare against master.
3. Github will see the latest commit into `gh-pages`, which will start the deployment process.
4. When it's done, you should be able to go to the docs page at https://luckyframework.github.io/lucky/. This will also show up on the new Github Deployments section of the repository.

**Pull request merged**
