### PR TITLE
attempt to fix tests in ci

### PR DESCRIPTION
**Pull request by bdtomlin**
## Purpose
route_not_found_handler_spec fails in CI #973 

## Description
#973 

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [x] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Comment by bdtomlin** [comment]
@jwoertink @paulcsmith  Whoohoo, tests passing. If you guys are ok with this solution let me know. I would like to add some comments to the tests and test_fallback_action.cr before it gets merged.

**Comment by bdtomlin** [comment]
Ok, @jwoertink. It should be good to go.

**Comment by jwoertink** [comment]
Awesome!

**Comment by paulcsmith** [comment]
Thank you!!

**Comment by edwardloveall** [comment]
Thank you so much @bdtomlin !

**Pull request merged**
