### PR TITLE
Added new module to disable FLoC

### LINKED ISSUE #1486: Disable FLoC by default
About Google's FLoC: https://www.howtogeek.com/724441/what-is-googles-floc-and-how-will-it-track-you-online/

Example of how Laravel disabled it: https://github.com/laravel/framework/commit/c42988a551ffdae0e70aa15959969732265789c0

We probably want to do something similar to Laravel and set the appropriate header if it's missing. That way users can set it if they want.

### PR DESCRIPTION
**Pull request by jwoertink**
## Purpose
Fixes #1486

## Description
This adds a new module to optionally disable FLoC. Just include it in your app, and it will set the appropriate header.

```crystal
class BrowserAction < Lucky::Action
  include Lucky::SecureHeaders::DisableFLoC
end
```

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [x] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Review by robacarp — APPROVED** [review]

**Comment by matthewmcgarvey** [comment]
@jwoertink The connected issue was to disable FLoC by default. What are your thoughts on that?

**Comment by jwoertink** [comment]
Reading around at a few articles, it seems like this is just a google experiment that probably won't last, or may change. I wouldn't be surprised if this is removed by the holidays 😂 

We can still do it by default by adding this module in to generated apps. Then if people want to opt in to this disable, they can just add the module in their BrowserAction for upgrades.

**Review by matthewmcgarvey — APPROVED** [review]

**Review by edwardloveall — APPROVED** [review]
I think it would be great to disable by default 🙂 It feels like the right thing to do and we want to be "batteries included" where it makes sense. I think it makes sense here!

**Comment by jwoertink** [comment]
ok, issue on CLI opened up! 👍

**Pull request merged**
