### PR TITLE
Fix failed specs in Crystal v1.13

### PR DESCRIPTION
**Pull request by akadusei**
## Purpose
Fix failed `Lucky::CookieJar` specs in Crystal v1.13

## Description 
`Lucky::CookieJar` specs fail in Crystal v1.13. This is related to [crystal-lang/crystal#14455](https://github.com/crystal-lang/crystal/pull/14455). This PR fixes that.

See <https://github.com/luckyframework/lucky/actions/runs/10340714956/job/28621689266>.

## Checklist
* [ ] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [ ] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Comment by akadusei** [comment]
There's also https://github.com/crystal-loot/exception_page/pull/49, which breaks Lucky when using `shard.edge.yml`.

**Comment by jwoertink** [comment]
Is this the right code? It looks like #1908 ? :thinking:

**Comment by akadusei** [comment]
Oops, sorry! I forgot to checkout `main` before working on this

**Comment by akadusei** [comment]
I can close this and send a new PR if that is preferred?

**Comment by jwoertink** [comment]
It's ok. I was going to merge the other anyway, so we'll just lump them together :D

**Review by jwoertink — APPROVED** [review]

**Pull request merged**
