### PR TITLE
Add 'style' tag to HTMLPage. Closes #91

### LINKED ISSUE #91: Add `style` tag helper

### PR DESCRIPTION
**Pull request by hanneskaeufler**
This allows you to specify raw css which will be output
into a style tag.

```crystal
style "body { background: blue; }
```

I am opening this early. Still debating whether to add a `block`ed version of this to do

```crystal
style do |css|
  css <<-CSS
  body { background: blue; }
  CSS
end
```

### CODE REVIEW

**Comment by hanneskaeufler** [comment]
I'm trying to :) But it also gets me thinking, when would you _not_ want raw output? Seeing as each css declaration is inside `{}` the curlies I don't see the point in calling `raw`?

**Comment by paulcsmith** [comment]
@hanneskaeufler After thinking about it...you're totally right. And you can accomplish the same thing with what you have already:

```crystal
style <<-CSS
  .all-the-css {}
CSS
```

So let's actually leave off the block version until someone comes up with a valid use case. Does that sound good to you?

**Comment by hanneskaeufler** [comment]
Sounds good to me. Been looking for the syntax you just posted all along, I really like that. Btw I don't think circle runs on this PR?

I changed the `WelcomePage` to use this helper. Didn't really run this, couldn't figure out how to use the local version of lucky to create a new test project to render the WelcomePage.

**Comment by paulcsmith** [comment]
Hmm. Not sure why CI isn't running. I pulled it locally and specs pass so I'll merge and investigate CI after. This looks great

**Pull request merged**
