### PR TITLE
Adding the optional routing in the to core

### PR DESCRIPTION
**Pull request by jwoertink**
## Purpose
Optional path params were added in to the router https://github.com/luckyframework/lucky_router/pull/18 but there was never a test done to see if Lucky core needed any updates. I added a spec to see if we needed to do anything, and it doesn't look like it.

## Checklist
* [ ] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [ ] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Comment by jwoertink** [comment]
Ah, gotcha. Ok, I'll take a look at that!

**Comment by paulcsmith** [comment]
Nice! I believe this is the spot: https://github.com/luckyframework/lucky/blob/72336b7d8bb96d90f1ca793d833435e9bd3a28e0/src/lucky/routable.cr#L198-L203. You'd want to check for `starts_with?("?:")` and use `params.get?()`. I think it'll also need to update the `with` and `route` helpers so that the params can be `nil` and they have a default value of `nil` which is somewhere in here I think :P https://github.com/luckyframework/lucky/blob/72336b7d8bb96d90f1ca793d833435e9bd3a28e0/src/lucky/routable.cr#L228-L243

**Comment by jwoertink** [comment]
😂  ok, so now that I just merged in that Avram update, this is failing. Should I include those Avram updates in this? Or make a separate PR to update that, then get that PR merged in to here? 🤔

**Comment by paulcsmith** [comment]
@jwoertink I think a separate PR with Avram fixes would be good since it’s small and we can get that in super fast

**Comment by jwoertink** [comment]
@paulcsmith Alright, I sent in that other PR and merged it in. It was a pretty small change. Let me know if you see any cases missing on this one.

**Pull request merged**
