### PR TITLE
moving ContentTypeHelpers to RequestTypeHelpers. 

### LINKED ISSUE #759: Checking a request type in actions
When you're inside an action, you have access to [these methods](https://github.com/luckyframework/lucky/blob/master/src/lucky/content_type_helpers.cr). One issue though is that these currently look for `Content-Type` header only. This works great in an API where you require a `Content-Type` to be passed, but from my recent findings, browsers don't pass this header with the request. That header is more for the response.

This means, doing this fails:

```crystal
route do
  if html?
    render(Home::Index)
  else
    raise Lucky::RouteNotFoundError.new(context)
  end
end
```

When I visit this page in both firefox, and chrome, here's the `headers` I have available:
```
HTTP::Headers{"Host" => "localhost:3001", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language" => "en-US,en;q=0.5", "Accept-Encoding" => "gzip, deflate", "Referer" => "http://localhost:3001/about", "DNT" => "1", "Connection" => "keep-alive", "Cookie" => "_session=abc123...", "Upgrade-Insecure-Requests" => "1", "Pragma" => "no-cache", "Cache-Control" => "no-cache"}
```

My thought is we can look at the accept header first then fallback to content-type after then finally an empty string. However, in doing this, it changes the logic a bit of how these are determined. If you look at my `Accept` header above, HTML is `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. This means more of a regex approach would be needed. The other thing is I feel like with an html request, `html?` and `xml?` should both return true, but for an xml request `html?` would be false, and `xml?` would be true.

### PR DESCRIPTION
**Pull request by jwoertink**
## Purpose
Fixes #759 

## Description
The `ContentTypeHelpers` has a method `html?` which checks the `Content-Type` header for "text/html". The problem is, at least with Firefox and Chrome, no `Content-Type` header is actually sent. So if your code relied on code like

```crystal
get "/" do
  if html?
    render HomePage
  else
    raise "only html here"
  end
end
```

Your app would always raise in a browser request. This does a few things

* Adds in a fallback check for the `Accept` header in case the `Content-Type` is blank
* Rename `ContentTypeHelpers` to `RequestTypeHelpers` since it checks more than just ContentType

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [x] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

### CODE REVIEW

**Comment by paulcsmith** [comment]
Github hates me this week. I can’t merge this no matter what I try 😂 

795BD863-910E-43AC-862A-D2CF1D588A99

Could you merge this?

**Comment by paulcsmith** [comment]
Github hates me this week. I can’t merge this no matter what I try 😂 

795BD863-910E-43AC-862A-D2CF1D588A99

Could you merge this?

**Comment by paulcsmith** [comment]
And when I tried to comment lol

55AEF569-02A6-4753-9A3B-E0A826115DCE

Looks like eventually it went through though...I hope

**Comment by jwoertink** [comment]
You win! You found the github bugs

**Pull request merged**
